#!/usr/bin/env bash
# Assemble sections-en/*.md into an arXiv/FSE-ready LaTeX source pipeline.
# Outputs a single Markdown file with a YAML metadata block (title, author,
# affiliation, abstract, keywords) followed by the body sections.
#
# Usage: ./scripts/assemble-latex-en.sh [output.md]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PAPER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SECTIONS_DIR="$PAPER_DIR/sections-en"
OUTPUT="${1:-$PAPER_DIR/manuscript-en-latex.md}"

FILES=(
    "01-introduction.md"
    "02-background.md"
    "03-the-eac-approach.md"
    "04-adl.md"
    "05-esa.md"
    "06-evaluation.md"
    "07-related-work.md"
    "08-conclusion.md"
)

python3 - "$SECTIONS_DIR" "$OUTPUT" "${FILES[@]}" << 'PYEOF'
import sys, os, re

sections_dir, output = sys.argv[1], sys.argv[2]
files = sys.argv[3:]

def read_section(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()

def promote_headers(text: str) -> str:
    """Promote each Markdown header by one level so # becomes ##, etc."""
    lines = text.splitlines()
    out = []
    for line in lines:
        m = re.match(r'^(#{1,6})\s', line)
        if m:
            level = len(m.group(1))
            if level < 6:
                line = '#' * (level + 1) + line[level:]
        out.append(line)
    return '\n'.join(out)

def extract_title_author_affil(text: str):
    """Parse 00-header.md of the form:
    # Title
    **Author Name**
    (Affiliation)
    """
    lines = text.strip().splitlines()
    title = lines[0].lstrip('#').strip() if lines else ''
    author = ''
    affil = ''
    for line in lines[1:]:
        line = line.strip()
        if not line:
            continue
        m = re.match(r'\*\*(.+?)\*\*', line)
        if m and not author:
            author = m.group(1).strip()
            continue
        m = re.match(r'\((.+?)\)', line)
        if m and not affil:
            affil = m.group(1).strip()
    return title, author, affil

def extract_abstract_keywords(text: str):
    """Parse 00-abstract.md of the form:
    # Abstract
    ... paragraphs ...
    **Keywords**: ...
    """
    lines = text.strip().splitlines()
    # Drop the '# Abstract' heading
    if lines and lines[0].lower().startswith('# abstract'):
        lines = lines[1:]

    # Find the keywords line
    keywords = ''
    body_lines = []
    kw_pattern = re.compile(r'^\*\*Keywords\*\*\s*[:：]\s*(.*)$', re.IGNORECASE)
    for line in lines:
        m = kw_pattern.match(line.strip())
        if m:
            keywords = m.group(1).strip()
            continue
        body_lines.append(line)

    # Remove trailing empty lines
    while body_lines and not body_lines[-1].strip():
        body_lines.pop()

    abstract = '\n'.join(body_lines).strip()
    return abstract, keywords

header_path = os.path.join(sections_dir, '00-header.md')
abstract_path = os.path.join(sections_dir, '00-abstract.md')

if not os.path.isfile(header_path):
    sys.exit(f'ERROR: missing {header_path}')
if not os.path.isfile(abstract_path):
    sys.exit(f'ERROR: missing {abstract_path}')

title, author, affil = extract_title_author_affil(read_section(header_path))
abstract, keywords = extract_abstract_keywords(read_section(abstract_path))

parts = [
    '---',
    f'title: "{title}"',
    f'author: "{author}"' if author else '',
    f'institute: "{affil}"' if affil else '',
    'date: "\\\\today"',
]

# Multi-line abstract needs YAML literal block
parts.append('abstract: |')
for line in abstract.splitlines():
    parts.append('  ' + line)

if keywords:
    parts.append(f'keywords: "{keywords}"')

parts.extend([
    '---',
    '',
    '<!-- Generated by scripts/assemble-latex-en.sh -->',
    '<!-- DO NOT EDIT THIS FILE — edit sections-en/*.md instead -->',
    '',
])

for fname in files:
    path = os.path.join(sections_dir, fname)
    if not os.path.isfile(path):
        sys.exit(f'ERROR: missing {path}')
    text = read_section(path)
    parts.append(text.rstrip('\n'))
    parts.append('')
    parts.append('')

with open(output, 'w', encoding='utf-8') as f:
    f.write('\n'.join(parts))

print(f'Assembled LaTeX manuscript → {output}')
print(f'  Sections: {len(files)}')
print(f'  Title:    {title}')
print(f'  Author:   {author}')
PYEOF
